# Generated by Django 5.0.2 on 2024-02-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
    ]
