# Generated by Django 5.0.2 on 2024-02-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_app', '0002_alter_servicio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='contenido',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(upload_to='servicios'),
        ),
    ]
